language: bash
services: docker
install: sudo apt-get -y install jq sed curl
jobs:
  include:
    - os: linux
      dist: bionic
      arch: arm64
      stage: Build Images
      script: bash docker_build.sh
      name:  Building and pushing ARMv8 images
    - dist: bionic
      arch: amd64
      name:  Building and pushing x86 images
      script: bash docker_build.sh
    - os: linux
      dist: focal
      arch: amd64
      stage: Push images
      name: Create and push docker manifest
      script: 
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - cat <<< $(jq '.+{"experimental":"enabled"}' ~/.docker/config.json) > ~/.docker/config.json
        - bash docker_push.sh